### ISSUE TITLE
IPs privadas y firewall

### ISSUE THREAD

**Issue by ulvida** [UdelaRInterior/ansible-role-firewall-proxmox#1]
En [esta línea](https://github.com/UdelaRInterior/ansible-role-firewall-proxmox/blob/46aff353862ed4cdedc070598a003ab3ad776446/files/etc/pve/firewall/cluster.fw#L17) del archivo `cluster.fwb`, dejamos pasar las IPs de redes privadas. 

No vamos a usar IPs privadas en la plataforma, por ende convendría excluirlas, no aceptarlas.

**Comment by santiagomr** [comment]
Correcto, aunque esas líneas son en realidad comentarios de ejemplos de uso para el role público. En nuestro proyecto contamos con un archivo cluster.fw que satisface las necesidades particulares.

**Comment by ulvida** [comment]
Ok, perdón. confundí ejemplo y valores propios de nuestra plataforma.
