### ISSUE TITLE
[BUG] Errors when pve_firewall_configure_cluster is true and configuring multiple hosts

### ISSUE THREAD

**Issue by exodious** [UdelaRInterior/ansible-role-firewall-proxmox#3]
**Describe the bug**
When running against multiple hosts and `pve_firewall_configure_cluster` is `true`, `FileNotFoundError` is raised intermittently during the copy task for `cluster.fw` ("Copy firewall configuration file for the CLUSTER (Called "Datacenter" in Proxmox web panel)"). Note that the file is in fact copied, so the errors are themselves somewhat erroneous. Not all of the repetitions of this task will error out.

**To Reproduce**
 - Configure your inventory with multiple LXC/Qemu hosts
 - Provide a `cluster.fw` file in the files folder with the other host firewall files.
 - Set `pve_firewall_configure_cluster` to `true` in your playbook
 - Run the playbook. Note this may require running multiple times to see the issue.

**Expected behavior**
Expect the `cluster.fw` file to be copied without errors.

**Screenshots**
N/A

**Characteristics of the execution environment (please complete the following information):**
 - OS (local): Pop!_OS 21.10
 - OS (remote): Proxmox VE 7.1-10
 - Ansible 2.10.8, Python 3.9.7
 - udelarinterior.firewall_proxmox v3.0.0

**Additional context**
I believe this is a concurrency issue because the one `cluster.fw` is trying to be written to by multiple parallel copy tasks, since the `cluster.fw` related tasks are being run for each host. In local testing with my fork, I have found that adding `run_once` with value `true` to these tasks resolves the issue. I will be submitting a PR with that fix.

**Comment by santiagomr** [comment]
Hi @exodious, thanks for the feedback and the bug report.

I agree with your analysis that it is a concurrency issue. The typical use case for which `run_once` exists.

PR merged.
